R xpart1
Rasel579/MVP_BIgin pull request #3
Opened 2021-08-08 09:44 UTC by Rasel579

2021-08-09 07:30 UTC, PeterBukhal-sovcombank requested changes
Есть критические замечания. Пока не принимаю.

2021-08-09 07:30 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/test_app/mvp_bigin/presentation/UserPresenter.kt
> +            .subscribe(
:100:

2021-08-09 07:30 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/test_app/mvp_bigin/presentation/UserPresenter.kt
> +        disposable = gitHubRepo
Используй `+=` таким образом: `disposables += usersRepo.getUsers().subscribe(...)` или расширение `addTo` так: `usersRepo.getUsers().subscribe(...).addTo(disposables)` это удобней.

2021-08-09 07:30 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/test_app/mvp_bigin/presentation/UserPresenter.kt
> +    private var disposable: Disposable? = null
Не забываем про `CompositeDisposable`

2021-08-09 07:30 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/test_app/mvp_bigin/model/GitHubRepo.kt
> +    fun getUsers(): Observable<GithubUser> = Observable.fromIterable(users)
:-1:  в этом случае правильней использовать Single.just() так как ответ всегда один, одним списком и не нужно каждый элемент списка превращать в сигнал.

2021-08-09 08:19 UTC, Rasel579 commented on app/src/main/java/com/test_app/mvp_bigin/presentation/UserPresenter.kt
> +            .subscribe(
А это что, нельзя так использовать?

2021-08-09 08:22 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/test_app/mvp_bigin/presentation/UserPresenter.kt
> +            .subscribe(
наоборот, все круто, 100 баллов) молодец.

2021-08-09 14:51 UTC, Rasel579 commented on app/src/main/java/com/test_app/mvp_bigin/presentation/UserPresenter.kt
> +        disposable = gitHubRepo
Изменил на CompositeDisposable() , до этого я пробовал, но не получалось, оказывается библиотека была не подключена rxkotlin

2021-08-09 14:53 UTC, Rasel579 commented on app/src/main/java/com/test_app/mvp_bigin/model/GitHubRepo.kt
> +    fun getUsers(): Observable<GithubUser> = Observable.fromIterable(users)
Ну я считал, что как в чате коннектся пользователи и они через листенер добавояются
Сделал на Singel

2021-08-09 14:54 UTC, Rasel579 commented on app/src/main/java/com/test_app/mvp_bigin/presentation/UserPresenter.kt
> +    private var disposable: Disposable? = null
Переделал, хорошо когда есть критика во время учебы)

2021-08-10 06:32 UTC, PeterBukhal-Geekbrains approved these changes
Есть замечания оставил комментарии в github, в целом отлично.

2021-08-10 06:32 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/test_app/mvp_bigin/MainActivity.kt
> +    private var binding: ActivityMainBinding? = null
Удобно использовать https://github.com/kirich1409/ViewBindingPropertyDelegate. См. последний пример с разбором ДЗ урока 2.

2021-08-10 06:32 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/test_app/mvp_bigin/model/GitHubRepo.kt
> +    fun getUsers(): Single<List<GithubUser>> = Single.just(users)
:+1:

2021-08-10 06:32 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/test_app/mvp_bigin/model/GithubUser.kt
> +) : Serializable
Предпочтительней все же использовать `Parcelize`

2021-08-10 06:32 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/test_app/mvp_bigin/model/MainModel.kt
>  class MainModel {
Думаю этот класс нам больше не нужен.

2021-08-10 06:32 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/test_app/mvp_bigin/navigation/UserScreen.kt
> +class UserScreen(private val githubUser: GithubUser) {
:+1:

2021-08-10 06:32 UTC, PeterBukhal-Geekbrains commented on app/src/main/java/com/test_app/mvp_bigin/presentation/UserPresenter.kt
> +            .map { it.find { user ->  user.login == userLogin } }
Такие вещи лучше вынести в репозиторий.

2021-08-15 19:30 UTC, merged